package Account;


import Account.Cart;
import Account.Home;
import Auxiliar.DataBase;
import Auxiliar.JTextFieldHintUI;
import Login.Login;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Razvan
 */
public class Products extends javax.swing.JFrame {

    /**
     * Creates new form Products
     */
    public Products() {
        initComponents();
        searchTextField.setUI(new JTextFieldHintUI("Search for products...", Color.gray));
        setTitle("Products");
        setResizable(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        //productLabel5.setText("<html>Line1<br>Line2</html>");

        displayProd(listPoz);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JLabel();
        prodPanel1 = new javax.swing.JPanel();
        pictureLabel1 = new javax.swing.JLabel();
        productLabel1 = new javax.swing.JLabel();
        priceLabel1 = new javax.swing.JLabel();
        addToCartLabel1 = new javax.swing.JLabel();
        prodPanel2 = new javax.swing.JPanel();
        pictureLabel2 = new javax.swing.JLabel();
        productLabel2 = new javax.swing.JLabel();
        priceLabel2 = new javax.swing.JLabel();
        addToCartLabel2 = new javax.swing.JLabel();
        prodPanel3 = new javax.swing.JPanel();
        pictureLabel3 = new javax.swing.JLabel();
        productLabel3 = new javax.swing.JLabel();
        priceLabel3 = new javax.swing.JLabel();
        addToCartLabel3 = new javax.swing.JLabel();
        prodPanel4 = new javax.swing.JPanel();
        pictureLabel4 = new javax.swing.JLabel();
        productLabel4 = new javax.swing.JLabel();
        priceLabel4 = new javax.swing.JLabel();
        addToCartLabel4 = new javax.swing.JLabel();
        prodPanel5 = new javax.swing.JPanel();
        pictureLabel5 = new javax.swing.JLabel();
        productLabel5 = new javax.swing.JLabel();
        priceLabel5 = new javax.swing.JLabel();
        addToCartLabel5 = new javax.swing.JLabel();
        leftPageButton = new javax.swing.JLabel();
        rightPageButton = new javax.swing.JLabel();
        toCartButton = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        qtyLabel = new javax.swing.JLabel();
        qtyComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel3.setBackground(new java.awt.Color(170, 131, 203));

        jPanel2.setBackground(new java.awt.Color(59, 36, 93));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        searchTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchTextFieldKeyPressed(evt);
            }
        });

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-icon.png"))); // NOI18N
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });

        prodPanel1.setBackground(new java.awt.Color(220, 220, 255));

        pictureLabel1.setBackground(new java.awt.Color(255, 255, 255));

        productLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        productLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productLabel1.setText("nume produs");

        priceLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        priceLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel1.setText("18.200 lei");

        addToCartLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addToCartLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addtocart.jpg"))); // NOI18N
        addToCartLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addToCartLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout prodPanel1Layout = new javax.swing.GroupLayout(prodPanel1);
        prodPanel1.setLayout(prodPanel1Layout);
        prodPanel1Layout.setHorizontalGroup(
            prodPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prodPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(prodPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pictureLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addToCartLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(priceLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        prodPanel1Layout.setVerticalGroup(
            prodPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prodPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(priceLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addToCartLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        prodPanel2.setBackground(new java.awt.Color(220, 220, 255));

        pictureLabel2.setBackground(new java.awt.Color(255, 255, 255));

        productLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        productLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productLabel2.setText("nume produs");

        priceLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        priceLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel2.setText("18.200 lei");

        addToCartLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addToCartLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addtocart.jpg"))); // NOI18N
        addToCartLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addToCartLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout prodPanel2Layout = new javax.swing.GroupLayout(prodPanel2);
        prodPanel2.setLayout(prodPanel2Layout);
        prodPanel2Layout.setHorizontalGroup(
            prodPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prodPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(prodPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addToCartLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(priceLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pictureLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        prodPanel2Layout.setVerticalGroup(
            prodPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prodPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(priceLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addToCartLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        prodPanel3.setBackground(new java.awt.Color(220, 220, 255));

        pictureLabel3.setBackground(new java.awt.Color(255, 255, 255));

        productLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        productLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productLabel3.setText("nume produs");

        priceLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        priceLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel3.setText("18.200 lei");

        addToCartLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addToCartLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addtocart.jpg"))); // NOI18N
        addToCartLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addToCartLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout prodPanel3Layout = new javax.swing.GroupLayout(prodPanel3);
        prodPanel3.setLayout(prodPanel3Layout);
        prodPanel3Layout.setHorizontalGroup(
            prodPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prodPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(prodPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addToCartLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(priceLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pictureLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        prodPanel3Layout.setVerticalGroup(
            prodPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prodPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(priceLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addToCartLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        prodPanel4.setBackground(new java.awt.Color(220, 220, 255));

        pictureLabel4.setBackground(new java.awt.Color(255, 255, 255));

        productLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        productLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productLabel4.setText("nume produs");

        priceLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        priceLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel4.setText("18.200 lei");

        addToCartLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addToCartLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addtocart.jpg"))); // NOI18N
        addToCartLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addToCartLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout prodPanel4Layout = new javax.swing.GroupLayout(prodPanel4);
        prodPanel4.setLayout(prodPanel4Layout);
        prodPanel4Layout.setHorizontalGroup(
            prodPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prodPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(prodPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addToCartLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(priceLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pictureLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        prodPanel4Layout.setVerticalGroup(
            prodPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prodPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(priceLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addToCartLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        prodPanel5.setBackground(new java.awt.Color(220, 220, 255));

        pictureLabel5.setBackground(new java.awt.Color(255, 255, 255));

        productLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        productLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productLabel5.setText("nume produs");

        priceLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        priceLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel5.setText("18.200 lei");

        addToCartLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addToCartLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addtocart.jpg"))); // NOI18N
        addToCartLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addToCartLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout prodPanel5Layout = new javax.swing.GroupLayout(prodPanel5);
        prodPanel5.setLayout(prodPanel5Layout);
        prodPanel5Layout.setHorizontalGroup(
            prodPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prodPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(prodPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addToCartLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(priceLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pictureLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        prodPanel5Layout.setVerticalGroup(
            prodPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prodPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(priceLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addToCartLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        leftPageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nextleftbutton.png"))); // NOI18N
        leftPageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leftPageButtonMouseClicked(evt);
            }
        });

        rightPageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nextrightbutton.png"))); // NOI18N
        rightPageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rightPageButtonMouseClicked(evt);
            }
        });

        toCartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cart.png"))); // NOI18N
        toCartButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toCartButtonMouseClicked(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        backButton.setForeground(new java.awt.Color(59, 36, 93));
        backButton.setText("Back");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        qtyLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        qtyLabel.setForeground(new java.awt.Color(59, 36, 93));
        qtyLabel.setText("Qty:");

        qtyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
            "1", "2", "3", "4", "5", "6", "7", "8", "9"
        }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(263, 263, 263)
                        .addComponent(toCartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139))
                            .addComponent(prodPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(prodPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(prodPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(prodPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(prodPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(qtyLabel)
                                .addGap(18, 18, 18)
                                .addComponent(qtyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(leftPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)
                                .addComponent(rightPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(570, 570, 570))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(searchTextField)
                        .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(toCartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prodPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qtyComboBox)
                            .addComponent(qtyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(leftPageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rightPageButton)))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        try {
            // TODO add your handling code here:
            listProd = DataBase.search(searchTextField.getText());
            listPoz = 0;
            displayProd(listPoz);
        } catch (SQLException ex) {
            Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchButtonMouseClicked

    private void leftPageButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftPageButtonMouseClicked
        // TODO add your handling code here:
        if (listPoz - 5 >= 0) {
            listPoz -= 5;
        }
        System.out.println(listPoz);
        displayProd(listPoz);
    }//GEN-LAST:event_leftPageButtonMouseClicked

    private void rightPageButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightPageButtonMouseClicked
        // TODO add your handling code here:
        if (listPoz + 5 < listProd.size()) {
            listPoz += 5;
        }

        displayProd(listPoz);
    }//GEN-LAST:event_rightPageButtonMouseClicked

    private void addToCartLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToCartLabel1MouseClicked
        try {
            // TODO add your handling code here:
            DataBase.addCart(productLabel1.getText(), Login.getIDAcc(), qtyComboBox.getSelectedIndex() + 1);
            qtyComboBox.setSelectedItem("1");
        } catch (SQLException ex) {
            Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addToCartLabel1MouseClicked

    private void addToCartLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToCartLabel2MouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            DataBase.addCart(productLabel2.getText(), Login.getIDAcc(), qtyComboBox.getSelectedIndex() + 1);
            qtyComboBox.setSelectedItem("1");
        } catch (SQLException ex) {
            Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addToCartLabel2MouseClicked

    private void addToCartLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToCartLabel3MouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            DataBase.addCart(productLabel3.getText(), Login.getIDAcc(), qtyComboBox.getSelectedIndex() + 1);
            qtyComboBox.setSelectedItem("1");
        } catch (SQLException ex) {
            Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addToCartLabel3MouseClicked

    private void addToCartLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToCartLabel4MouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            DataBase.addCart(productLabel4.getText(), Login.getIDAcc(), qtyComboBox.getSelectedIndex() + 1);
            qtyComboBox.setSelectedItem("1");
        } catch (SQLException ex) {
            Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addToCartLabel4MouseClicked

    private void addToCartLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToCartLabel5MouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            DataBase.addCart(productLabel5.getText(), Login.getIDAcc(), qtyComboBox.getSelectedIndex() + 1);
            qtyComboBox.setSelectedItem("1");
        } catch (SQLException ex) {
            Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addToCartLabel5MouseClicked

    private void toCartButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toCartButtonMouseClicked
        // TODO add your handling code here:
        new Cart().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_toCartButtonMouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonMouseClicked

    private void searchTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextFieldKeyPressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            if (evt.getKeyChar() >= 'a' && evt.getKeyChar() <= 'z' || evt.getKeyChar() >= 'A' && evt.getKeyChar() <= 'Z') {
                listProd = DataBase.search(searchTextField.getText() + evt.getKeyChar());
            } else {
                listProd = DataBase.search(searchTextField.getText());
            }
            listPoz = 0;
            displayProd(listPoz);
        } catch (SQLException ex) {
            Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchTextFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Products().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addToCartLabel1;
    private javax.swing.JLabel addToCartLabel2;
    private javax.swing.JLabel addToCartLabel3;
    private javax.swing.JLabel addToCartLabel4;
    private javax.swing.JLabel addToCartLabel5;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel leftPageButton;
    private javax.swing.JLabel pictureLabel1;
    private javax.swing.JLabel pictureLabel2;
    private javax.swing.JLabel pictureLabel3;
    private javax.swing.JLabel pictureLabel4;
    private javax.swing.JLabel pictureLabel5;
    private javax.swing.JLabel priceLabel1;
    private javax.swing.JLabel priceLabel2;
    private javax.swing.JLabel priceLabel3;
    private javax.swing.JLabel priceLabel4;
    private javax.swing.JLabel priceLabel5;
    private javax.swing.JPanel prodPanel1;
    private javax.swing.JPanel prodPanel2;
    private javax.swing.JPanel prodPanel3;
    private javax.swing.JPanel prodPanel4;
    private javax.swing.JPanel prodPanel5;
    private javax.swing.JLabel productLabel1;
    private javax.swing.JLabel productLabel2;
    private javax.swing.JLabel productLabel3;
    private javax.swing.JLabel productLabel4;
    private javax.swing.JLabel productLabel5;
    private javax.swing.JComboBox<String> qtyComboBox;
    private javax.swing.JLabel qtyLabel;
    private javax.swing.JLabel rightPageButton;
    private javax.swing.JLabel searchButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JLabel toCartButton;
    // End of variables declaration//GEN-END:variables
    private static ArrayList<String> listProd;
    private static int listPoz;

    static {
        try {
            listProd = DataBase.returnProducts();
            listPoz = 0;
        } catch (SQLException ex) {
            Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void displayProd(int i) {

        javax.swing.JLabel[][] prodPanelArray = {
            {pictureLabel1, productLabel1, priceLabel1, addToCartLabel1},
            {pictureLabel2, productLabel2, priceLabel2, addToCartLabel1},
            {pictureLabel3, productLabel3, priceLabel3, addToCartLabel1},
            {pictureLabel4, productLabel4, priceLabel4, addToCartLabel1},
            {pictureLabel5, productLabel5, priceLabel5, addToCartLabel1},};

        if (listProd.size() == i) {
            prodPanel1.setVisible(false);
            prodPanel2.setVisible(false);
            prodPanel3.setVisible(false);
            prodPanel4.setVisible(false);
            prodPanel5.setVisible(false);
        } else if (listProd.size() - 1 == i) {
            prodPanel1.setVisible(true);
            prodPanel2.setVisible(false);
            prodPanel3.setVisible(false);
            prodPanel4.setVisible(false);
            prodPanel5.setVisible(false);
        } else if (listProd.size() - 2 == i) {
            prodPanel1.setVisible(true);
            prodPanel2.setVisible(true);
            prodPanel3.setVisible(false);
            prodPanel4.setVisible(false);
            prodPanel5.setVisible(false);
        } else if (listProd.size() - 3 == i) {
            prodPanel1.setVisible(true);
            prodPanel2.setVisible(true);
            prodPanel3.setVisible(true);
            prodPanel4.setVisible(false);
            prodPanel5.setVisible(false);
        } else if (listProd.size() - 4 == i) {
            prodPanel1.setVisible(true);
            prodPanel2.setVisible(true);
            prodPanel3.setVisible(true);
            prodPanel4.setVisible(true);
            prodPanel5.setVisible(false);
        } else {
            prodPanel1.setVisible(true);
            prodPanel2.setVisible(true);
            prodPanel3.setVisible(true);
            prodPanel4.setVisible(true);
            prodPanel5.setVisible(true);
        }

        for (int poz = 0; i < listProd.size() && poz < 5; i++, poz++) {
            String[] cuv = listProd.get(i).split(" ");
            prodPanelArray[poz][0].setIcon(new ImageIcon(cuv[0]));
            String nume = "";
            for (int j = 3; j < cuv.length - 1; j++) {
                nume = nume + cuv[j] + " ";
            }
            nume += cuv[cuv.length - 1];
            prodPanelArray[poz][1].setText(nume);
            prodPanelArray[poz][2].setText(cuv[1] + " lei");
            if (Integer.parseInt(cuv[2]) == 0) {
                prodPanelArray[poz][3].setVisible(false);
            }
        }

    }

}
