package Administrator;


import Auxiliar.DataBase;
import Administrator.AdminPanel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Razvan
 */
public class SalesReport extends javax.swing.JFrame {

    /**
     * Creates new form SalesReport
     */
    public SalesReport() {
        initComponents();
        setTitle("Sales report");
        setResizable(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        productBasedButton = new javax.swing.JButton();
        categoryBasedButton = new javax.swing.JButton();
        userBasedButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel3.setBackground(new java.awt.Color(170, 131, 203));

        jPanel2.setBackground(new java.awt.Color(59, 36, 93));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(59, 36, 93));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Sales Report");

        productBasedButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        productBasedButton.setForeground(new java.awt.Color(59, 36, 93));
        productBasedButton.setText("Product");
        productBasedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productBasedButtonMouseClicked(evt);
            }
        });

        categoryBasedButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        categoryBasedButton.setForeground(new java.awt.Color(59, 36, 93));
        categoryBasedButton.setText("Category");
        categoryBasedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoryBasedButtonMouseClicked(evt);
            }
        });

        userBasedButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        userBasedButton.setForeground(new java.awt.Color(59, 36, 93));
        userBasedButton.setText("User");
        userBasedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userBasedButtonMouseClicked(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        backButton.setForeground(new java.awt.Color(59, 36, 93));
        backButton.setText("Back");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        String[] columnName = null;
        Object[][] data = null;

        switch(tableType) {
            case 1:
            data = new Object[report.size()][3];
            columnName = new String[]{"Product name", "Quantity sold", "Total income"};
            int k = 0;
            for(int i = 0; i < report.size(); i++) {

                String[] cuv = report.get(i).split(" ");
                if(!cuv[0].equals("null")) {

                    data[k][1] = cuv[0];
                    data[k][2] = cuv[1] + " lei";
                    String nume = "";
                    for(int j = 2; j < cuv.length - 1; j++) {
                        nume = nume + cuv[j] + " ";
                    }
                    nume += cuv[cuv.length - 1];
                    data[k][0] = nume;
                    k++;
                }

            }
            break;
            case 2:
            columnName = new String[]{"Category", "Qty sold"};
            data = new Object[report.size()][2];
            ArrayList<String> ListCateg = null;
            try {
                ListCateg = DataBase.getCategories();
            } catch (SQLException ex) {
                Logger.getLogger(SalesReport.class.getName()).log(Level.SEVERE, null, ex);
            }
            int l =0;
            for(int i = 0; i < report.size(); i++) {
                if(!report.get(i).equals("null")) {
                    data[l][0] = ListCateg.get(i);
                    data[l][1] = report.get(i);
                    l++;
                }
            }

            break;
            case 3:
            data = new Object[report.size()][4];
            columnName = new String[]{"User ID", "Order No.", "Price paid", "Date"};
            for(int i = 0; i < report.size(); i++) {
                String[] cuv = report.get(i).split(" ");
                data[i][0] = cuv[0];
                data[i][1] = cuv[1];
                data[i][2] = cuv[2] + " lei";
                data[i][3] = cuv[3];

            }

            break;
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(data, columnName){

            public boolean isCellEditable(int row, int column)
            {
                return column == 4;
            }
        }
    );
    jScrollPane1.setViewportView(jTable1);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(75, 75, 75)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(categoryBasedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(productBasedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(userBasedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(48, 48, 48)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(56, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(129, 129, 129)
                    .addComponent(productBasedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(categoryBasedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(userBasedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(48, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productBasedButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productBasedButtonMouseClicked
        // TODO add your handling code here:
        tableType = 1;
        report = new ArrayList<>();
        ArrayList<String> ListProd = null;
        try {
            ListProd = DataBase.returnProducts();
        } catch (SQLException ex) {
            Logger.getLogger(SalesReport.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < ListProd.size(); i++) {
            String[] cuv = ListProd.get(i).split(" ");
            String nume = "";
            for (int j = 3; j < cuv.length - 1; j++) {
                nume = nume + cuv[j] + " ";
            }
            nume += cuv[cuv.length - 1];

            try {
                report.addAll(DataBase.raportProdus(nume));
            } catch (SQLException ex) {
                Logger.getLogger(SalesReport.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        new SalesReport().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_productBasedButtonMouseClicked

    private void categoryBasedButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryBasedButtonMouseClicked
        // TODO add your handling code here:
        tableType = 2;

        report = new ArrayList<>();
        try {
            ArrayList<String> ListCateg = DataBase.getCategories();
            for (int i = 0; i < ListCateg.size(); i++) {
                report.addAll(DataBase.raportCategorie(ListCateg.get(i)));
                System.out.println(ListCateg.get(i));
            }

        } catch (SQLException ex) {
            Logger.getLogger(SalesReport.class.getName()).log(Level.SEVERE, null, ex);
        }

        new SalesReport().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_categoryBasedButtonMouseClicked

    private void userBasedButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userBasedButtonMouseClicked
        // TODO add your handling code here:
        tableType = 3;
        report = new ArrayList<>();
        try {
            for (int i = 0; i < DataBase.getAccNo(); i++) {
                report.addAll(DataBase.raportCont(i + 1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(SalesReport.class.getName()).log(Level.SEVERE, null, ex);
        }
        new SalesReport().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userBasedButtonMouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        new AdminPanel().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesReport().setVisible(true);
            }
        });
    }

    private static int tableType;

    static {
        tableType = 1;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton categoryBasedButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton productBasedButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton userBasedButton;
    // End of variables declaration//GEN-END:variables
    private static ArrayList<String> report;

    static {
        report = new ArrayList<>();
        ArrayList<String> ListProd = null;
        try {
            ListProd = DataBase.returnProducts();
        } catch (SQLException ex) {
            Logger.getLogger(SalesReport.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < ListProd.size(); i++) {
            String[] cuv = ListProd.get(i).split(" ");
            String nume = "";
            for (int j = 3; j < cuv.length - 1; j++) {
                nume = nume + cuv[j] + " ";
            }
            nume += cuv[cuv.length - 1];

            try {
                report.addAll(DataBase.raportProdus(nume));
            } catch (SQLException ex) {
                Logger.getLogger(SalesReport.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

}
